### PR TITLE
fix(longevity): 'to' commit may be computed wrongly for deleted lines…

### PR DESCRIPTION
**Pull request by asurkov**
do not add lines for deleted files since their lines will be added when a diff is processed (double addition)

### CODE REVIEW

**Comment by anatolykislov** [comment]
Should this PR be closed?

**Comment by asurkov** [comment]
no, why?

**Comment by anatolykislov** [comment]
Because #30 contains the commit from this PR and new commit. Why did you split #29 and #30 ?

**Comment by asurkov** [comment]
Right, it's on top of this branch. That's a thing I don't like about git, you cannot work on on top of other work and hide that fact from your reviewer and probably not confuse him :)

I follow 'one problem - one pull request' rule, it's much easier for tracking, reviewing and all.

So is my understanding correct that you approved both pull requests by approving #30?

**Comment by anatolykislov** [comment]
Approved both.

**Pull request closed without merging**
